language: node_js
node_js: '8'
jobs:
  include:
  - stage: test
    script: npm test
  - stage: npm release
    script: echo "Deploying to npm ..."
    deploy:
      provider: npm
      email: telegraph.engineering@telepgraph.co.uk
      api_key:
        secure: DdwigUyOOCH5myiTXgI8d9u49s2f+FGCbPimHEFUXBGQpPg23nHfhoYd6PBvuM5djljfBcCgrZ+9wNalMNR/TNFp25NwpJRY3aoKBgtn37oT5EBlwzmVOB2cmd9y3r90Qo/L2TsJZ2MDrylpNTqwYwz7Zm0+xt46VHjyEmManDj+ajETFzGAHmSL2sadSfl8pkFiGxNtdWRV26tAft7fIKGL5nQpATyXCkX1l4jdm5RKSo/cpmQvIszslr8VfZWk8wdu/eTNjcgqgM3Azrd7LETf/Phz2elEwRyLPvcaG7QfsBz5u1nNzBiUpEh9rJmyne+v0phaJQ7XqgF7ITKbNfB32zVTtgCiHPM3FtLLKA0fVMVsiY6dVafKF09Yszlk4zD5yT6+JG9gifaLOWx8DPYrx6Wr4Dwop8lWO/OxGTQzWSeEUoxwdMT18MC+th4x330Vjbx6N6njHtHlisMZ2u9GkaxUOfmv5R5wV5sU/bzhdNWCXSRQDESHWAkZrpKKzl8wtk1opj9W8aqic9OP6YSPh5M59fC5Jmy7WBlKYlLdEV7XyO31Ak4dpjd8JR8Vw0RaapcmWGaymzmcmUh0WJGT/ZRFW8V2bLJg+4Rul7DkqfP4czzkJgU+KHEH8RwpNHetu8YLirWWetVMzW54xqRyBVyu/cOvpM7x5+bzMf0=
      on:
        tags: true
        repo: telegraph/node-validator
